#!/usr/bin/env rake
require_relative  'lib/database'
require "roda"
require "sequel"

namespace :db do
  database = Database.start
  database_name = Database.name
  table = :accounts

  task :create_table do
    puts "Creating table '#{table.to_s}' in " + database_name.upcase

    database.create_table table do
      primary_key :id
      String :address
      Integer :balance
    end
    puts "Table '#{table.to_s}' was created in " + database_name.upcase
  end

  task :drop_table do
    puts "Droping table '#{table.to_s}' from " + database_name.upcase

    database.drop_table table
    puts "Table '#{table.to_s}' was dropped from " + database_name.upcase
  end
end
